spring:
  profiles:
    group: 
      "dev-profile": "dev,jwt" 
      "ops-profile": "ops,jwt"
    active : dev-profile

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://146.56.177.153:3306/oci_mariaDB
    username: root
    password: 1

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true